import { StyleSheet } from "react-native";
import { colors } from "./Colors.ts";

export const sensorScreenStyles = StyleSheet.create({
    mainContainer: {
        flex: 1,
        backgroundColor: colors.bgLight,
        padding: 20,
        justifyContent: "center",
        alignItems: "center",
    },
    sdcSuccess: {
        padding: 20,
        marginVertical: 10,
        width: '90%',
        justifyContent: 'center',
        alignItems: 'center',
        borderStyle: 'solid',
        borderWidth: 2,
        borderRadius: 15,
        borderColor: colors.success,
        backgroundColor: colors.bgLight2,
        shadowColor: colors.dark,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    sdcError: {
        padding: 20,
        marginVertical: 10,
        width: '90%',
        justifyContent: 'center',
        alignItems: 'center',
        borderStyle: 'solid',
        borderWidth: 2,
        borderRadius: 15,
        borderColor: colors.danger,
        backgroundColor: colors.bgLight2,
        shadowColor: colors.dark,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    sdcDisconnected: {
        padding: 20,
        marginVertical: 10,
        width: '90%',
        justifyContent: 'center',
        alignItems: 'center',
        borderStyle: 'solid',
        borderWidth: 2,
        borderRadius: 15,
        borderColor: colors.earth,
        backgroundColor: colors.bgLight2,
        shadowColor: colors.dark,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    sensorStatusContainer: {
        alignItems: 'center',
    },
    sensorStatusIndicator: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 15,
    },
    actionsContainer: {
        marginTop: 20,
        gap: 10
    },
    modalContainer: {
        flex: 1,
        backgroundColor: colors.bgLight,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 24,
    },
    modalContent: {
        width: '90%',
        maxWidth: 600,
        backgroundColor: colors.bgLight2,
        borderRadius: 15,
        padding: 20,
        gap: 16,
        borderWidth: 2,
        borderColor: colors.secondary,
        shadowColor: colors.dark,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 5,
    },
    pickerModalContainer: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.3)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 24,
    },
    pickerModalContent: {
        width: '90%',
        maxWidth: 500,
        maxHeight: '75%',
        backgroundColor: colors.bgLight2,
        borderRadius: 15,
        padding: 20,
        borderWidth: 2,
        borderColor: colors.secondary,
        shadowColor: colors.dark,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 5,
    },
    pickerScrollView: {
        maxHeight: 360,
    },
    textarea: {
        marginVertical: 12,
        height: 120,
        padding: 12,
        borderWidth: 2,
        borderColor: colors.secondary,
        borderRadius: 12,
        textAlignVertical: 'top',
        backgroundColor: colors.bgLight,
        fontSize: 16,
    },
    soilIDInput: {
        marginVertical: 12,
        padding: 12,
        borderWidth: 2,
        borderColor: colors.secondary,
        borderRadius: 12,
        backgroundColor: colors.bgLight,
        fontSize: 16,
    },
    selectInput: {
        marginVertical: 12,
        padding: 12,
        borderWidth: 2,
        borderColor: colors.secondary,
        borderRadius: 12,
        backgroundColor: colors.bgLight,
        justifyContent: 'center',
        minHeight: 48,
    },
    selectInputText: {
        fontSize: 16,
        color: colors.dark,
        fontWeight: '500',
    },
    modalOption: {
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: colors.accent,
        backgroundColor: colors.bgLight,
        borderRadius: 8,
        marginVertical: 2,
    },
    modalOptionText: {
        fontSize: 16,
        color: colors.dark,
        fontWeight: '500',
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: colors.dark,
        marginBottom: 16,
        textAlign: 'center',
    },
    sensorDataContainer: {
        flexDirection: 'row',
        gap: 10,
    },
    cardsContainer: {
        width: '100%',
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginTop: 12,
    },
    halfCard: {
        width: '48%',
        backgroundColor: colors.bgLight,
        borderRadius: 12,
        padding: 12,
        marginBottom: 12,
        borderWidth: 2,
        borderColor: colors.secondary,
        shadowColor: colors.dark,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
        minHeight: 96,
        justifyContent: 'space-between',
    },
    fullCard: {
        width: '100%',
        backgroundColor: colors.bgLight,
        borderRadius: 12,
        padding: 12,
        marginBottom: 12,
        borderWidth: 2,
        borderColor: colors.secondary,
        shadowColor: colors.dark,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
        minHeight: 96,
        justifyContent: 'space-between',
    },
    cardHeader: {
        fontSize: 14,
        fontWeight: '700',
        color: colors.dark,
        marginBottom: 6,
    },
    cardRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    commentsActionContainer: {
        justifyContent: 'space-between',
        gap: 10,
        marginTop: 10,
    },
    // Full Screen Comments Modal Styles
    fullScreenModalContainer: {
        flex: 1,
        backgroundColor: colors.bgLight,
        padding: 20,
    },
    fullScreenModalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
        paddingBottom: 15,
        borderBottomWidth: 2,
        borderBottomColor: colors.secondary,
    },
    fullScreenModalTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: colors.dark,
    },
    fullScreenModalCloseButton: {
        padding: 8,
        borderRadius: 20,
        backgroundColor: colors.danger,
    },
    fullScreenModalCloseText: {
        color: colors.light,
        fontSize: 18,
        fontWeight: 'bold',
    },
    fullScreenModalTextInput: {
        flex: 1,
        backgroundColor: colors.bgLight2,
        borderRadius: 12,
        padding: 16,
        fontSize: 16,
        textAlignVertical: 'top',
        borderWidth: 2,
        borderColor: colors.secondary,
        marginBottom: 20,
    },
    fullScreenModalButtonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 12,
    },
    fullScreenModalButton: {
        flex: 1,
        paddingVertical: 16,
        borderRadius: 12,
        alignItems: 'center',
    },
    fullScreenModalButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.light,
    },
    fullScreenModalCancelButton: {
        backgroundColor: colors.danger,
    },
    fullScreenModalSaveButton: {
        backgroundColor: colors.success,
    },
    adviceContainer: {
        marginTop: 8,
        paddingTop: 6,
        borderTopWidth: 1,
        borderTopColor: colors.accent,
    },
    adviceStatusText: {
        fontSize: 12,
        fontWeight: '700',
    },
    adviceRecommendationText: {
        fontSize: 12,
        color: colors.dark,
        marginTop: 2,
    },
    adviceStatusOptimal: {
        color: colors.success,
    },
    adviceStatusWarning: {
        color: colors.warning,
    },
    adviceStatusCritical: {
        color: colors.danger,
    },
    // Narra Suitability Card Styles (matches fullCard style)
    narraSuitabilityCard: {
        width: '100%',
        backgroundColor: colors.bgLight,
        borderRadius: 12,
        padding: 12,
        marginBottom: 12,
        borderWidth: 2,
        borderColor: colors.secondary,
        shadowColor: colors.dark,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    narraSuitabilityHeader: {
        fontSize: 14,
        fontWeight: '700',
        color: colors.dark,
        marginBottom: 6,
    },
    narraSuitabilityContent: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginVertical: 4,
    },
    narraSuitabilityLabel: {
        fontSize: 18,
        fontWeight: '700',
    },
    narraSuitabilityPercentage: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.dark,
    },
    narraSuitabilityDescription: {
        fontSize: 12,
        color: colors.dark,
        marginTop: 6,
        paddingTop: 6,
        borderTopWidth: 1,
        borderTopColor: colors.accent,
    },
    suitabilityIdeal: {
        color: colors.success,
    },
    suitabilityGood: {
        color: colors.success,
    },
    suitabilityModerate: {
        color: colors.warning,
    },
    suitabilityPoor: {
        color: '#FF9800',
    },
    suitabilityUnsuitable: {
        color: colors.danger,
    },
    // Prediction Card Styles (matches fullCard style)
    predictionCard: {
        width: '100%',
        backgroundColor: colors.bgLight,
        borderRadius: 12,
        padding: 12,
        marginBottom: 12,
        borderWidth: 2,
        borderColor: colors.secondary,
        shadowColor: colors.dark,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    predictionCardHeader: {
        fontSize: 14,
        fontWeight: '700',
        color: colors.dark,
        marginBottom: 6,
    },
    predictionValue: {
        fontSize: 18,
        fontWeight: '700',
        color: colors.primary,
        marginBottom: 4,
    },
    soilTypeMatchesContainer: {
        marginTop: 6,
        paddingTop: 6,
        borderTopWidth: 1,
        borderTopColor: colors.accent,
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
    },
    soilTypeMatchText: {
        fontSize: 12,
        color: colors.dark,
    },
});