import { StyleSheet } from "react-native";
import { colors } from "./Colors.ts";

export const sensorScreenStyles = StyleSheet.create({
    mainContainer: {
        flex: 1,
        backgroundColor: colors.bgLight,
        padding: 20,
        justifyContent: "center",
        alignItems: "center",
    },
    sdcSuccess: {
        padding: 20,
        marginVertical: 10,
        width: '90%',
        justifyContent: 'center',
        alignItems: 'center',
        borderStyle: 'solid',
        borderWidth: 2,
        borderRadius: 15,
        borderColor: colors.success,
        backgroundColor: colors.bgLight2,
        shadowColor: colors.dark,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    sdcError: {
        padding: 20,
        marginVertical: 10,
        width: '90%',
        justifyContent: 'center',
        alignItems: 'center',
        borderStyle: 'solid',
        borderWidth: 2,
        borderRadius: 15,
        borderColor: colors.danger,
        backgroundColor: colors.bgLight2,
        shadowColor: colors.dark,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    sdcDisconnected: {
        padding: 20,
        marginVertical: 10,
        width: '90%',
        justifyContent: 'center',
        alignItems: 'center',
        borderStyle: 'solid',
        borderWidth: 2,
        borderRadius: 15,
        borderColor: colors.earth,
        backgroundColor: colors.bgLight2,
        shadowColor: colors.dark,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    sensorStatusContainer: {
        alignItems: 'center',
    },
    sensorStatusIndicator: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 15,
    },
    actionsContainer: {
        marginTop: 20,
        gap: 10
    },
    button: {
        backgroundColor: colors.primary,
        padding: 15,
        borderRadius: 12,
        marginVertical: 5,
        shadowColor: colors.dark,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    modalContainer: {
        flex: 1,
        backgroundColor: colors.bgLight,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 24,
    },
    modalContent: {
        width: '90%',
        maxWidth: 600,
        backgroundColor: colors.bgLight2,
        borderRadius: 15,
        padding: 20,
        gap: 16,
        borderWidth: 2,
        borderColor: colors.secondary,
        shadowColor: colors.dark,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 5,
    },
    textarea: {
        marginVertical: 12,
        height: 120,
        padding: 12,
        borderWidth: 2,
        borderColor: colors.secondary,
        borderRadius: 12,
        textAlignVertical: 'top',
        backgroundColor: colors.bgLight,
        fontSize: 16,
    },
    soilIDInput: {
        marginVertical: 12,
        padding: 12,
        borderWidth: 2,
        borderColor: colors.secondary,
        borderRadius: 12,
        backgroundColor: colors.bgLight,
        fontSize: 16,
    },
    selectInput: {
        marginVertical: 12,
        padding: 12,
        borderWidth: 2,
        borderColor: colors.secondary,
        borderRadius: 12,
        backgroundColor: colors.bgLight,
        justifyContent: 'center',
        minHeight: 48,
    },
    selectInputText: {
        fontSize: 16,
        color: colors.dark,
        fontWeight: '500',
    },
    modalOption: {
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: colors.accent,
        backgroundColor: colors.bgLight,
        borderRadius: 8,
        marginVertical: 2,
    },
    modalOptionText: {
        fontSize: 16,
        color: colors.dark,
        fontWeight: '500',
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: colors.dark,
        marginBottom: 16,
        textAlign: 'center',
    },
    sensorDataContainer: {
        flexDirection: 'row',
        gap: 10,
    },
    cardsContainer: {
        width: '100%',
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginTop: 12,
    },
    card: {
        width: '48%',
        backgroundColor: colors.bgLight,
        borderRadius: 12,
        padding: 12,
        marginBottom: 12,
        borderWidth: 2,
        borderColor: colors.secondary,
        shadowColor: colors.dark,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
        minHeight: 96,
        justifyContent: 'space-between',
    },
    npkCard: {
        width: '100%',
        backgroundColor: colors.bgLight,
        borderRadius: 12,
        padding: 12,
        marginBottom: 12,
        borderWidth: 2,
        borderColor: colors.secondary,
        shadowColor: colors.dark,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
        minHeight: 96,
        justifyContent: 'space-between',
    },
    cardHeader: {
        fontSize: 14,
        fontWeight: '700',
        color: colors.dark,
        marginBottom: 6,
    },
    cardRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
});